//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automated_Phone_Copying_charging_renaming.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^yyMMdd^")]
        public string DirectoriesinDF1formula {
            get {
                return ((string)(this["DirectoriesinDF1formula"]));
            }
            set {
                this["DirectoriesinDF1formula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%NAME%.%EXTENSION%")]
        public string DF1Filesformula {
            get {
                return ((string)(this["DF1Filesformula"]));
            }
            set {
                this["DF1Filesformula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%T1%?T1?\'_\'%AN%?AN?\'_\'%L1%?L1?\'_\'%CN%_^yyMMdd^_%NAME%.%EXTENSION%")]
        public string DF2Filesformula {
            get {
                return ((string)(this["DF2Filesformula"]));
            }
            set {
                this["DF2Filesformula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^yyMMdd^")]
        public string DirectoriesinDF2formula {
            get {
                return ((string)(this["DirectoriesinDF2formula"]));
            }
            set {
                this["DirectoriesinDF2formula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000-09-30")]
        public global::System.DateTime fromdate {
            get {
                return ((global::System.DateTime)(this["fromdate"]));
            }
            set {
                this["fromdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2023-11-13")]
        public global::System.DateTime todate {
            get {
                return ((global::System.DateTime)(this["todate"]));
            }
            set {
                this["todate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Copytodf1 {
            get {
                return ((bool)(this["Copytodf1"]));
            }
            set {
                this["Copytodf1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Copytodf2 {
            get {
                return ((bool)(this["Copytodf2"]));
            }
            set {
                this["Copytodf2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool selectfilesbycreationdate {
            get {
                return ((bool)(this["selectfilesbycreationdate"]));
            }
            set {
                this["selectfilesbycreationdate"] = value;
            }
        }
    }
}
